// Code generated by mockery. DO NOT EDIT.

package verifiers

import mock "github.com/stretchr/testify/mock"

// HashFunctionMock is an autogenerated mock type for the HashFunction type
type HashFunctionMock struct {
	mock.Mock
}

type HashFunctionMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HashFunctionMock) EXPECT() *HashFunctionMock_Expecter {
	return &HashFunctionMock_Expecter{mock: &_m.Mock}
}

// CalculateHash provides a mock function with given fields: filename, previousHash
func (_m *HashFunctionMock) CalculateHash(filename string, previousHash string) (string, error) {
	ret := _m.Called(filename, previousHash)

	if len(ret) == 0 {
		panic("no return value specified for CalculateHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(filename, previousHash)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(filename, previousHash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(filename, previousHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HashFunctionMock_CalculateHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateHash'
type HashFunctionMock_CalculateHash_Call struct {
	*mock.Call
}

// CalculateHash is a helper method to define mock.On call
//   - filename string
//   - previousHash string
func (_e *HashFunctionMock_Expecter) CalculateHash(filename interface{}, previousHash interface{}) *HashFunctionMock_CalculateHash_Call {
	return &HashFunctionMock_CalculateHash_Call{Call: _e.mock.On("CalculateHash", filename, previousHash)}
}

func (_c *HashFunctionMock_CalculateHash_Call) Run(run func(filename string, previousHash string)) *HashFunctionMock_CalculateHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *HashFunctionMock_CalculateHash_Call) Return(_a0 string, _a1 error) *HashFunctionMock_CalculateHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HashFunctionMock_CalculateHash_Call) RunAndReturn(run func(string, string) (string, error)) *HashFunctionMock_CalculateHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewHashFunctionMock creates a new instance of HashFunctionMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashFunctionMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashFunctionMock {
	mock := &HashFunctionMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
