with-expecter: True
resolve-type-alias: False
disable-version-string: True
inpackage: True
all: True

filename: "{{.InterfaceName  | snakecase | lower }}_mock.gen.go"
dir: "{{.InterfaceDir}}"
outpkg: "{{.PackageName}}"
mockname: "{{.InterfaceName}}Mock"

packages:
  github.com/ChristophBe/migration-tool:
    config:
      recursive: True



